server:
    port: 9090
    servlet:
        context-path: /

spring:
    data:
        redis:
            host: localhost
            port: 6379
            password: 011202
            connect-timeout: 3000
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/contract?serverTimezone=Asia/Shanghai
        username: root
        password: womima011202

mybatis-plus:
    global-config:
        db-config:
            id-type: auto
    configuration:
        map-underscore-to-camel-case: false
        auto-mapping-behavior: full
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mybatis.mapper/*.xml
